create table if not exists USERS
(
    user_id  bigint  primary key auto_increment,
    email    text not null,
    login    text not null,
    name     text,
    birthday date
);

create table if not exists FRIENDSHIP_STATUS
(
    status_id bigint primary key,
    name      text
);

create table if not exists FRIENDS
(
    friend_id bigint references USERS (user_id),
    user_id   bigint references USERS (user_id),
    status_id bigint references FRIENDSHIP_STATUS (status_id)

);

create table if not exists GENRES
(
    id   bigint primary key,
    name text
);

create table if not exists MPA_RATING
(
    id   bigint primary key,
    name text
);

create table if not exists FILMS
(
    film_id     bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    name        text not null,
    description text,
    releaseDate date,
    duration    integer check (duration > 0),
    rating_id   bigint references MPA_RATING (id) NOT NULL
);

create table if not exists LIKES
(
    user_id bigint references USERS (user_id),
    film_id bigint references FILMS (film_id)
);

create table if not exists FILM_GENRES
(
    film_id  bigint references FILMS (film_id),
    genre_id bigint references GENRES (id)
);




